//
//  LoginModels.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
  
  struct Login {
    struct Request {
      var endpoint: String?
      var username: String?
      var password: String?
    }
    
    struct Response {
      enum ResponseError: Error {
        case webService
        case noInternet
        case missingInformation
        case invalidEndpoint
      }
      
      var error: ResponseError?
    }
    
    struct ViewModel {
      struct Error: ErrorAlertInterface {
        var title: String
        var message: String
        var button: String
      }
      
      var error: ViewModel.Error?
    }
  }
  
}
