//
//  LoginPresenter.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentLogin(_ response: Login.Login.Response)
}

class LoginPresenter: LoginPresentationLogic {
  weak var viewController: LoginDisplayLogic?

  // MARK: - Presentation Function
  func presentLogin(_ response: Login.Login.Response) {
    guard let error = response.error else {
      viewController?.displayLoginSuccess(Login.Login.ViewModel(error: nil))
      return
    }
    
    var errorAlert = Login.Login.ViewModel.Error(title: "Error", message: "", button: "Okay")
    switch error {
    case .webService:
      errorAlert.message = "Cannot Connect To Service. Please Try Again."
    case .noInternet:
      errorAlert.message = "Connection Error. Please Enable Internet Connection."
    case .missingInformation:
      errorAlert.message = "Missing Information. Please Input All Required Information and Try Again."
    case .invalidEndpoint:
      errorAlert.message = "Endpoint Incorrect. Please Check Endpoint."
    }
    
    viewController?.displayLoginFailure(Login.Login.ViewModel(error: errorAlert))
  }
  
}
