//
//  MainPresenter.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
  func presentCheckLists(_ response: Main.FetchCheckLists.Response)
}

class MainPresenter: MainPresentationLogic {
  weak var viewController: MainDisplayLogic?

  // MARK: - Presentation Function
  func presentCheckLists(_ response: Main.FetchCheckLists.Response) {
    let checkLists = response.checkLists?.map { $0.toCheckListModel() } ?? []
    viewController?.displayCheckLists(Main.FetchCheckLists.ViewModel(checkLists: checkLists))
  }
  
}

private extension CheckList {
  func toCheckListModel() -> CheckListModel {
    let formatter = DateFormatter()
    formatter.dateFormat = "dd/MM/yyyy HH:mm:ss"
    return CheckListModel(identifier: id,
                          idName: "ID: \(id)",
                          groupName: groupName,
                          licensePlate: licensePlate.replacingOccurrences(of: "/", with: " "),
                          status: status,
                          version: "v. \(1)",
                          createdDateString: formatter.string(from: createdDate),
                          lastModifiedDateString: formatter.string(from: lastModifiedDate))
  }
}
