//
//  MainRouter.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
  func navigateToDetail()
}

protocol MainDataPassing {
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  var detailViewController: DetailViewController? {
    guard let navigationController = viewController?.splitViewController?.viewControllers.last as? UINavigationController else { return nil }
    return navigationController.viewControllers.first as? DetailViewController
  }
  
  // MARK: - Route Functions
  func routeToDetail() {
    viewController?.collapseDetailViewController = false
    detailViewController?.navigationItem.leftBarButtonItem = viewController?.splitViewController?.displayModeButtonItem
    detailViewController?.navigationItem.leftItemsSupplementBackButton = true
    
    detailViewController?.router?.dataStore?.checkListId = dataStore?.selectedCheckList?.id
    detailViewController?.router?.dataStore?.isNeedFetching = true
    detailViewController?.checkConfirmationNeeded()
  }
  
  // MARK: - Navigate Functions
  func navigateToDetail() {
    routeToDetail()
  }
  
  // MARK: - Passing Data Functions
  
}
