//
//  MainInteractor.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
  func fetchCheckLists(_ request: Main.FetchCheckLists.Request)
  func selectedCheckList(_ request: Main.SelectedCheckList.Request)
}

protocol MainDataStore: class {
  var selectedCheckList: CheckList? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
  var presenter: MainPresentationLogic?
  
  lazy var apiWorker = GateCheckApiWorker()
  var checkLists: [CheckList] = []
  var selectedCheckList: CheckList?
  
  // MARK: - Business Functions
  func fetchCheckLists(_ request: Main.FetchCheckLists.Request) {
    apiWorker.getCheckLists(groupName: request.groupName, status: request.status, createdDate: request.createdDate)
    { [weak self] (result) in
      self?.checkLists = result.value ?? []
      let response = Main.FetchCheckLists.Response(checkLists: result.value, error: result.error)
      self?.presenter?.presentCheckLists(response)
    }
  }
  
  func selectedCheckList(_ request: Main.SelectedCheckList.Request) {
    selectedCheckList = checkLists.first { $0.id == request.id }
  }
  
}
