//
//  MainModels.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
  
  struct FetchCheckLists {
    struct Request {
      var groupName: String?
      var status: CheckListStatus?
      var createdDate: Date?
    }
    
    struct Response {
      var checkLists: [CheckList]?
      var error: APIError?
    }
    
    struct ViewModel {
      var checkLists: [CheckListModel]
    }
  }
  
  struct SelectedCheckList {
    struct Request {
      var id: String
    }
    
    struct Response { }
    struct ViewModel { }
  }
  
}
