//
//  DetailRouter.swift
//  Gate Check
//
//  Created by Rawipon Srivibha on 17/12/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic {
  
}

protocol DetailDataPassing {
  var dataStore: DetailDataStore? { get }
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing {
  weak var viewController: DetailViewController?
  var dataStore: DetailDataStore?
  
  // MARK: - Route Functions
  
  // MARK: - Navigate Functions
  
  // MARK: - Passing Data Functions
  
}
